#!/bin/sh
# File is symlinked, actually stored in /usr/bin

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$status" = "Discharging" ];
then
	iconStatus=🔋
elif [ "$status" = "Charging" ];
then
	iconStatus=🔌
fi

echo "$iconStatus $capacity%"
